### ISSUE TITLE
Make file-handling robust for errors

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tkoziara/solfec#55]
```
Would request that a solver crash leaves the database in a state where the 
model can be re-opened using the -v flag. This would massively help with 
debugging.
```

Original issue reported on code.google.com by `steve.br...@atkinsglobal.com` on 8 Apr 2014 at 4:14

**Comment by tkoziara** [comment]
This is resolved when using HDF5 format and since the previous XDR based output is now deprecated I am closing this.
