### ISSUE TITLE
Build issues with ec8aaef

### ISSUE THREAD

**Issue by stevebrasier** [tkoziara/solfec#56]
Tried to compile this - something's wrong with the Costy code. Reverted to a847321 which built ok except for hdf5 error which I'll log separately.

Don't seem to be able to attach files so here's the output from ec8aaef:

SB07365S@athos2:~$ cd solfec/
SB07365S@athos2:~/solfec$ make all
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES  -c -o obj/solfec.o solfec.c
(cd ext/blopex && make)
make[1]: entrant dans le rÃ©pertoire Â« /athos-gpfssata/home/SB07365S/solfec/ext/blopex Â»
Making multivector ...
make[2]: entrant dans le rÃ©pertoire Â« /athos-gpfssata/home/SB07365S/solfec/ext/blopex/multivector Â»
cc -O -I. -I../utilities   -c -o multivector.o multivector.c
cc -O -I. -I../utilities   -c -o multiserial.o multiserial.c
cc -O -I. -I../utilities   -c -o pcg_multi.o pcg_multi.c
make[2]: quittant le rÃ©pertoire Â« /athos-gpfssata/home/SB07365S/solfec/ext/blopex/multivector Â»

Making krylov ...
make[2]: entrant dans le rÃ©pertoire Â« /athos-gpfssata/home/SB07365S/solfec/ext/blopex/krylov Â»
cc -O -I. -I../utilities -I../multivector  -c -o lobpcg.o lobpcg.c
make[2]: quittant le rÃ©pertoire Â« /athos-gpfssata/home/SB07365S/solfec/ext/blopex/krylov Â»

Making utilities ...
make[2]: entrant dans le rÃ©pertoire Â« /athos-gpfssata/home/SB07365S/solfec/ext/blopex/utilities Â»
cc -O -I.   -c -o fortran_matrix.o fortran_matrix.c
make[2]: quittant le rÃ©pertoire Â« /athos-gpfssata/home/SB07365S/solfec/ext/blopex/utilities Â»

Building libBLOPEX.a ...
cd lib && ar -rvcu libBLOPEX.a ./*.o
a - ./fortran_matrix.o
a - ./lobpcg.o
a - ./multiserial.o
a - ./multivector.o
a - ./pcg_multi.o
cd lib && ranlib libBLOPEX.a
mv lib/libBLOPEX.a ../../obj/
mkdir -p include
cp -fp  multivector/interpreter.h multivector/multivector.h multivector/multiserial.h multivector/pcg_multi.h krylov/lobpcg.h utilities/fortran_matrix.h utilities/fortran_interpreter.h utilities/fortran_options.h include
make[1]: quittant le rÃ©pertoire Â« /athos-gpfssata/home/SB07365S/solfec/ext/blopex Â»
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -c -o obj/fastlz.o ext/fastlz.c
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -c -o obj/csparse.o ext/csparse.c
cc -DOSTYPE_LINUX -O0 -c -o obj/predicates.o ext/predicates.c
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -c -o obj/err.o err.c
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -c -o obj/alg.o alg.c
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -c -o obj/mem.o mem.c
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -c -o obj/pck.o pck.c
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -c -o obj/kdt.o kdt.c
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -c -o obj/map.o map.c
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -c -o obj/set.o set.c
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -c -o obj/skp.o skp.c
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -c -o obj/svk.o svk.c
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -Iext/blopex/include -c -o obj/mtx.o mtx.c
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -c -o obj/tms.o tms.c
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -c -o obj/xyt.o xyt.c
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -c -o obj/dyr.o dyr.c
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -c -o obj/swp.o swp.c
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -c -o obj/hsh.o hsh.c
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -c -o obj/gjk.o gjk.c
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -c -o obj/tsi.o tsi.c
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -c -o obj/hul.o hul.c
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -c -o obj/tri.o tri.c
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -c -o obj/cvi.o cvi.c
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -c -o obj/spx.o spx.c
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -c -o obj/cvx.o cvx.c
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -c -o obj/hyb.o hyb.c
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -c -o obj/msh.o msh.c
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -c -o obj/sph.o sph.c
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -c -o obj/eli.o eli.c
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -c -o obj/shp.o shp.c
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -I/usr/include/python2.6 -c -o obj/fld.o fld.c
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -c -o obj/sps.o sps.c
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -c -o obj/mat.o mat.c
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -c -o obj/goc.o goc.c
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -c -o obj/cmp.o cmp.c
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -I/usr/include/python2.6 -c -o obj/dbs.o dbs.c
cc -std=c99 -DPOSIX -w -pedantic -O3 -funroll-loops     -DTIMERS -DHDF5 -I/usr/include/hdf5  -DLOCAL_BODIES -c -o obj/scf.o scf.c
g++ -w -pedantic -O3 -funroll-loops     -I.. -c -o obj/costy.o costy/costy.cpp
costy/costy.cpp:16:17: error: sol.h: Aucun fichier ou dossier de ce type
costy/costy.cpp:17:17: error: dom.h: Aucun fichier ou dossier de ce type
costy/costy.cpp:18:17: error: msh.h: Aucun fichier ou dossier de ce type
In file included from costy/costy.cpp:21:
costy/costy.h:11: error: âMESHâ was not declared in this scope
costy/costy.h:11: error: âmshâ was not declared in this scope
costy/costy.h:11: error: expected primary-expression before âdoubleâ
costy/costy.h:11: error: expected primary-expression before âdoubleâ
costy/costy.h:11: error: expected primary-expression before âdoubleâ
costy/costy.h:11: error: expected primary-expression before âdoubleâ
costy/costy.h:11: error: initializer expression list treated as compound expression
costy/costy.h:13: error: âBODYâ was not declared in this scope
costy/costy.h:13: error: â_bodâ was not declared in this scope
costy/costy.h:13: error: expected primary-expression before âdoubleâ
costy/costy.h:13: error: expected primary-expression before âdoubleâ
costy/costy.h:13: error: expected primary-expression before âcharâ
costy/costy.h:13: error: initializer expression list treated as compound expression
costy/costy.cpp: In function âint findIndx(Face*, Edge&)â:
costy/costy.cpp:58: error: invalid use of incomplete type âstruct faceâ
costy/costy.cpp:25: error: forward declaration of âstruct faceâ
costy/costy.cpp:62: error: invalid use of incomplete type âstruct faceâ
costy/costy.cpp:25: error: forward declaration of âstruct faceâ
costy/costy.cpp:64: error: invalid use of incomplete type âstruct faceâ
costy/costy.cpp:25: error: forward declaration of âstruct faceâ
costy/costy.cpp:65: error: invalid use of incomplete type âstruct faceâ
costy/costy.cpp:25: error: forward declaration of âstruct faceâ
costy/costy.cpp:66: error: invalid use of incomplete type âstruct faceâ
costy/costy.cpp:25: error: forward declaration of âstruct faceâ
costy/costy.cpp: At global scope:
costy/costy.cpp:81: error: variable or field âfindConvexEdgesâ declared void
costy/costy.cpp:81: error: âMESHâ was not declared in this scope
costy/costy.cpp:81: error: âmshâ was not declared in this scope
costy/costy.cpp:81: error: expected primary-expression before â&â token
costy/costy.cpp:81: error: âedgesâ was not declared in this scope
costy/costy.cpp:81: error: expected primary-expression before âdoubleâ
costy/costy.cpp:81: error: expected primary-expression before âdoubleâ
costy/costy.cpp:81: error: expected primary-expression before â&â token
costy/costy.cpp:81: error: âconvexEdgesâ was not declared in this scope
make: *** [obj/costy.o] Erreur 1

**Comment by tkoziara** [comment]
No longer needed; Steve; 26 March 2016;
