### ISSUE TITLE
Build issues with c4a2b1e

### ISSUE THREAD

**Issue by stevebrasier** [tkoziara/solfec#58]
make solfec gives:
....
g++  -o solfec obj/solfec.o -Lobj -lsolfec -lkrylov -ldmumps -lmetis -ltet -lBLOPEX -lm -lstdc++ -L/usr/lib -llapack -L/usr/lib -lblas  -lpython2.6   -lgfortran -Lext/mumps/libseq -lmpiseq
obj/libtet.a(tetsol.o): In function `tetrahedralize1':
/usr/local/solfec/solfec-src/ext/tetgen/tetsol.cxx:119: undefined reference to `refineEdgesTetgen'
collect2: ld returned 1 exit status
make: *** [solfec] Error 1

Looks like the relative reference to ../../costy/costy.h isn't working for some reason

**Comment by tkoziara** [comment]
Try playing with the order of linking: swap -lsolfec and -ltet in line 121 of the Makefile. Let me know, it works on my computer. We this doesn't help, we can switch this code off.

**Comment by stevebrasier** [comment]
Hi,

I tried this but it got worse maybe:

…
g++  -o solfec obj/solfec.o -Lobj -ltet -lkrylov -ldmumps -lmetis -lsolfec -lBLOPEX -lm -lstdc++ -L/usr/lib -llapack -L/usr/lib -lblas -lglut -lGLU -lpython2.6   -lgfortran -Lext/mumps/libseq -lmpiseq
obj/libsolfec.a(lng.o): In function `lng_TETRAHEDRALIZE':
/scratch0/bras6717/test-solfec/solfec/lng.c:5265: undefined reference to `tetrahedralize1'
/scratch0/bras6717/test-solfec/solfec/lng.c:5274: undefined reference to `tetrahedralize2'
obj/libsolfec.a(mtx.o): In function `inv_vec':
/scratch0/bras6717/test-solfec/solfec/mtx.c:891: undefined reference to `dmumps_c'
obj/libsolfec.a(mtx.o): In function `vec_inv':
/scratch0/bras6717/test-solfec/solfec/mtx.c:915: undefined reference to `dmumps_c'
obj/libsolfec.a(mtx.o): In function `csc_doinv':
/scratch0/bras6717/test-solfec/solfec/mtx.c:1685: undefined reference to `dmumps_c'
/scratch0/bras6717/test-solfec/solfec/mtx.c:1709: undefined reference to `dmumps_c'
obj/libsolfec.a(mtx.o): In function `csc_inverse':
/scratch0/bras6717/test-solfec/solfec/mtx.c:1733: undefined reference to `dmumps_c'
obj/libsolfec.a(mtx.o):/scratch0/bras6717/test-solfec/solfec/mtx.c:1910: more undefined references to `dmumps_c' follow
obj/libsolfec.a(msh.o): In function `MESH_Split':
/scratch0/bras6717/test-solfec/solfec/msh.c:1886: undefined reference to `tetrahedralize3'
/scratch0/bras6717/test-solfec/solfec/msh.c:1907: undefined reference to `tetrahedralize3'
/scratch0/bras6717/test-solfec/solfec/msh.c:1916: undefined reference to `tetrahedralize3'
obj/libsolfec.a(msh.o): In function `MESH_Partition':
/scratch0/bras6717/test-solfec/solfec/msh.c:2620: undefined reference to `METIS_PartGraphRecursive'
/scratch0/bras6717/test-solfec/solfec/msh.c:2621: undefined reference to `METIS_PartGraphKway'
obj/libsolfec.a(rbmm.o): In function `rbmm_main':
/scratch0/bras6717/test-solfec/solfec/costy/rbmm.cpp:368: undefined reference to `tetrahedralize1'
obj/libsolfec.a(nts.o): In function `solve':
/scratch0/bras6717/test-solfec/solfec/nts.c:1118: undefined reference to `hypre_FlexGMRESFunctionsCreate'
/scratch0/bras6717/test-solfec/solfec/nts.c:1124: undefined reference to `hypre_FlexGMRESCreate'
/scratch0/bras6717/test-solfec/solfec/nts.c:1129: undefined reference to `hypre__global_error'
/scratch0/bras6717/test-solfec/solfec/nts.c:1130: undefined reference to `hypre_FlexGMRESSetTol'
/scratch0/bras6717/test-solfec/solfec/nts.c:1131: undefined reference to `hypre_FlexGMRESSetMinIter'
/scratch0/bras6717/test-solfec/solfec/nts.c:1132: undefined reference to `hypre_FlexGMRESSetMaxIter'
/scratch0/bras6717/test-solfec/solfec/nts.c:1133: undefined reference to `hypre_FlexGMRESSetAbsoluteTol'
/scratch0/bras6717/test-solfec/solfec/nts.c:1134: undefined reference to `hypre_FlexGMRESSetup'
/scratch0/bras6717/test-solfec/solfec/nts.c:1135: undefined reference to `hypre_FlexGMRESSolve'
/scratch0/bras6717/test-solfec/solfec/nts.c:1136: undefined reference to `hypre_FlexGMRESGetNumIterations'
/scratch0/bras6717/test-solfec/solfec/nts.c:1137: undefined reference to `hypre_FlexGMRESDestroy'
obj/libsolfec.a(tts.o): In function `linear_solve':
/scratch0/bras6717/test-solfec/solfec/tts.c:538: undefined reference to `hypre_FlexGMRESFunctionsCreate'
/scratch0/bras6717/test-solfec/solfec/tts.c:544: undefined reference to `hypre_FlexGMRESCreate'
/scratch0/bras6717/test-solfec/solfec/tts.c:546: undefined reference to `hypre__global_error'
/scratch0/bras6717/test-solfec/solfec/tts.c:547: undefined reference to `hypre_FlexGMRESSetTol'
/scratch0/bras6717/test-solfec/solfec/tts.c:548: undefined reference to `hypre_FlexGMRESSetMinIter'
/scratch0/bras6717/test-solfec/solfec/tts.c:549: undefined reference to `hypre_FlexGMRESSetMaxIter'
/scratch0/bras6717/test-solfec/solfec/tts.c:550: undefined reference to `hypre_FlexGMRESSetAbsoluteTol'
/scratch0/bras6717/test-solfec/solfec/tts.c:551: undefined reference to `hypre_FlexGMRESSetup'
/scratch0/bras6717/test-solfec/solfec/tts.c:552: undefined reference to `hypre_FlexGMRESSolve'
/scratch0/bras6717/test-solfec/solfec/tts.c:553: undefined reference to `hypre_FlexGMRESGetNumIterations'
/scratch0/bras6717/test-solfec/solfec/tts.c:554: undefined reference to `hypre_FlexGMRESDestroy'
obj/libsolfec.a(fra.o): In function `Fracture_Export_Yaffems':
/scratch0/bras6717/test-solfec/solfec/fra.c:397: undefined reference to `tetrahedralize1'
obj/libsolfec.a(fra.o): In function `Fracture_Export_MoFEM':
/scratch0/bras6717/test-solfec/solfec/fra.c:574: undefined reference to `tetrahedralize1'
collect2: ld returned 1 exit status
make: *** [solfec] Error 1

Steve

**Comment by tkoziara** [comment]
Costy's code is now moved to a branch and this should be OK now. Closing.
