### ISSUE TITLE
Simuler the liaison ressort (spring) between two nodes in Solfec 

### ISSUE THREAD

**Issue by nicolasmecamas** [tkoziara/solfec#60]
Hi developer,
Could you please show me how I can simulate the liaison ressort (spring) with the stiffness K between two nodes?
Thank you in advance,
Nicolas,

**Comment by vacary** [comment]
I am not in the developper team, but is there any bar finite element for doing that ?

**Comment by tkoziara** [comment]
:) Wow; Hi Nicolas & Vincent

Perhaps this can help?
http://parmes.org/solfec/user/constraints.html#put-spring
In combination with this example:
https://github.com/tkoziara/solfec/blob/master/inp/shockabs.py

Best regards,
Tomek

**Comment by nicolasmecamas** [comment]
Hi Tomek,
Thank you for your reply. However, I want to set a resort with constant stiffness K. In the doc that you send me, K depend on velocity and on gap.
Thank you in advance,
Nicolas

**Comment by tkoziara** [comment]
Hi; The spring function is defined by the user; In the example the spring has a constant stiffness K=1000 (multiplying the stroke) and includes a damper (with coefficient 100, multiplying relative velocity); You can decide what the function contains:) Is this OK? T.

**Comment by tkoziara** [comment]
Nicolas,
Is it OK to close this issue? I am guessing it should be by now.
Tomek

**Comment by nicolasmecamas** [comment]
Hi Tomek,
It is OK,
many thank,
Nicolas
