### ISSUE TITLE
Stress at Gaussian points

### ISSUE THREAD

**Issue by stevebrasier** [tkoziara/solfec#62]
Would be useful to be able to determine the stress at these locations.

Not sure whether access via STRESS(), HISTORY(), or both is preferable.

Alternatively I guess there could be a way to return the coordinates of gauss points, then the above routines could be used unchanged?

**Comment by tkoziara** [comment]
This is now available via:
MESH.surface_integration_points()
MESH.volume_integration_points()
See [docs](http://parmes.org/solfec/user/geometry.html#id3) and [example](https://github.com/tkoziara/solfec/blob/master/inp/devel/integration-points.py);
:) Tomek
