### ISSUE TITLE
Access to mesh for a BODY

### ISSUE THREAD

**Issue by stevebrasier** [tkoziara/solfec#63]
Could be useful to be able to access the mesh (nodes, elements and connectivity) data once a body has been created (which currently empties the mesh, presumably as part of memory management).

I have reviewed the members and methods provided by MESH objects and they all look potentially useful (obviously read-only); would providing access to the MESH object itself (or a proxy supporting the same members/methods) be possible e.g. as BODY.mesh?

**Comment by tkoziara** [comment]
Hi Steve,
BODY.mesh has now been added; See [docs](http://parmes.org/solfec/user/body.html#id9);
:)
Tomek
