### ISSUE TITLE
Error of drag force for projectile FEM

### ISSUE THREAD

**Issue by nicolasmecamas** [tkoziara/solfec#64]
Hi Tomek,
I am doing a test of projectile. Could you find enclosed the test?
When I use "RIGID" behaviour, It work. But when I use FE (deformable element), it does not work and issue the following error:

----------------------------------------------------------------------------------------
INITIALLY DOFS 513, BODIES: 1 (OBS: 0, RIG: 0, PRB: 0, FEM: 1)
----------------------------------------------------------------------------------------
TIME: 0 ... DOMAIN ... (STEP: 0.000167) ValueError: Tuple of invalid size was returned from FORCE callback

Could you please help me to debug it?
Thank you in advance,
Nicolas

[Project_Def_test.py.docx](https://github.com/tkoziara/solfec/files/949989/Project_Def_test.py.docx)

**Comment by tkoziara** [comment]
Hi Nicolas,

Please find attached a modified version of your file. Few things to mention:

1. As in [the test's description](http://parmes.org/solfec/validation/projectile.html) the drag force is minus mass times velocity; for FEM the needs to be generalised into minus mass matrix times velocity vector; this is now reflected in the modified file;

2. In the callback gathering data for plotting I used DISPLACEMENT to track position of the point (0, 0, 0); At the end I included the comparison with the analytical result and the plotting code as in the original validation test;

3. There seems to be an issue with the mass of the body (the dimensions of the sphere or the mass density) as compared to the original analytical value; this is flagged in the code; nonetheless the result seems to be correct:) this goes back to the findings of Newton and Galileo, yes?:)

Best regards,
Tomek

[Project_Def_test_V1.1.zip](https://github.com/tkoziara/solfec/files/951518/Project_Def_test_V1.1.zip)

**Comment by nicolasmecamas** [comment]
Hi Tomek,
I updated the Solfec and lunched your file, but It generates the following error:
Could you please verify?
Thank in advance,
Nicolas

Ubuntu version: 14.04

Python version: 2.7

===========




peter@peter-VirtualBox:​~/Works_Cao/Benchmarks_check/B​-12$ solfec_new Project_Def_test_V1.1.py 
Body mass: 4037.90256065 reference mass: 0.45359237
These seem to differe a little bit? :)
Running simulation ... 0%
Traceback (most recent call last):
 File "Project_Def_test_V1.1.py", line 1078, in air_force
 f = -(M * u)
 File "/usr/lib/python2.​7/dist-packages/scipy/sparse/b​ase.py",​ line 285, in __mul__
 M,N = self.shape
 File "/usr/lib/python2.​7/dist-packages/scipy/sparse/b​ase.py",​ line 440, in __getattr__
 raise AttributeError(attr + " not found")
AttributeError: shape not found
solfec_new: malloc.c:3987: _int_free: Assertion `p->fd_nextsize->bk_nextsize == p' failed.
Aborted (core dumped)


===============

**Comment by tkoziara** [comment]
This could be related to the version of scipy and on-the-fly conversion from Python Tuple for u into a numpy array; Try, at the top of the file:
`import numpy as np`
and replace 
`f = -(M * u)`
with
`f = -(M * np.array(u))`

**Comment by nicolasmecamas** [comment]
I tried with your suggestions but it generates once again the following error: 

peter@peter-VirtualBox:~/Works_Cao/Benchmarks_check/B-12$ solfec_new Project_Def_test_V1.1.py
Body mass: 4037.90256065 reference mass: 0.45359237
These seem to differe a little bit? :)
Running simulation ... 0%
Traceback (most recent call last):
File "Project_Def_test_V1.1.py", line 1079, in air_force
f = -(M * np.array(u))
File "/usr/lib/python2.7/dist-packages/scipy/sparse/base.py", line 285, in __mul__
M,N = self.shape
File "/usr/lib/python2.7/dist-packages/scipy/sparse/base.py", line 440, in __getattr__
raise AttributeError(attr + " not found")
AttributeError: shape not found
solfec_new: malloc.c:3987: _int_free: Assertion `p->fd_nextsize->bk_nextsize == p' failed.
Aborted (core dumped)

**Comment by tkoziara** [comment]
OK, here is a little piece of code:

`import scipy`
`import numpy`
`print 'Sicipy version:', scipy.__version__`
`print 'Numpy version:', numpy.__version__`

Can you paste it into a *.py file and run it using solfec?
Here is what I am getting:

> Sicipy version: 0.18.1
> Numpy version: 1.12.0

**Comment by nicolasmecamas** [comment]
Hi Tomek,
I am getting:
Sicipy version: 0.13.3
Numpy version: 1.8.1

**Comment by tkoziara** [comment]
Why don't you [try this](https://askubuntu.com/questions/682825/how-to-update-to-the-latest-numpy-and-scipy-on-ubuntu-14-04lts)? What seemed to have helped was:
`sudo easy_install --upgrade numpy`
`sudo easy_install --upgrade scipy`
Let me know if it worked;

**Comment by nicolasmecamas** [comment]
I had to re-install Ubuntu and update
* Scipy version: 0.19.0
* Numpy version: 1.12.1 
But the test has not yet worked. It generates the following error:
Could you please help me debug it?

=========================
peter@peter:~/Works_Cao/Bench$ solfec_new Project_Def_test_V1.1.py
Scipy version: 0.19.0
Numpy version: 1.12.1
Body mass: 4037.90256065 reference mass: 0.45359237
These seem to differe a little bit? :)
Running simulation ...----------------------------------------------------------------------------------------
INITIALLY DOFS 513, BODIES: 1 (OBS: 0, RIG: 0, PRB: 0, FEM: 1)
----------------------------------------------------------------------------------------
TIME: 0 ... DOMAIN ...  (STEP: 0.000167) CONDET (HYBRID) ... LOCDYN ... SOLVER ...
PENALTY_SOLVER: applying springs and dashpots...
PENALTY_SOLVER: solving non-contact constraints...
GAUSS_SEIDEL: iteration:    0  error:  0.00e+00  merit:  0.00e+00
GAUSS_SEIDEL: iteration:    1  error:  0.00e+00  merit:  0.00e+00
----------------------------------------------------------------------------------------
     BODIES:        1
      BOXES:      310
CONSTRAINTS:        0
 SPARSIFIED:        0
----------------------------------------------------------------------------------------
TIMINT: 73%, CONUPD:  2%, CONDET: 25%, LOCDYN:  0%, CONSOL  0%, PARBAL:  0%
----------------------------------------------------------------------------------------
            Estimated end in  0 days,  0 hours,  0 minutes and  0 seconds
========================================================================================

Traceback (most recent call last):
  File "Project_Def_test_V1.1.py", line 1085, in air_force
    f = -(M * np.array(u))
  File "/usr/local/lib/python2.7/dist-packages/scipy/sparse/base.py", line 351, in __mul__
    M, N = self.shape
  File "/usr/local/lib/python2.7/dist-packages/scipy/sparse/base.py", line 576, in __getattr__
    raise AttributeError(attr + " not found")
AttributeError: shape not found
solfec_new: malloc.c:3987: _int_free: Assertion `p->fd_nextsize->bk_nextsize == p' failed.
Aborted (core dumped)
===================================

**Comment by tkoziara** [comment]
Hi:) I edited your comment a little bit, since `---` and `===` bits were interpreted as headings, resulting in large fonts;

I appreciate that you re-installed Ubunutu:) See also [parmes.org/vbox](http://parmes.org/vbox) were you can find a Linux VirtualBox image which can be useful for testing; I just run this example on this system resulting in:

```
parmes@parmes-linux:~/Temp/i64_projectile_fem$ solfec Project_Def_test_V1.1.py 
Body mass: 4037.90256065 reference mass: 0.45359237
These seem to differe a little bit? :)
Running simulation ... 99%
Computed x distance: 86.135; Reference distance: 86.138; Relative error: 0.000
Plotting  out/Projectile_test_V1.1/projectile.png ...
```

For me this works the same, with or without, the `np.array(u)` bit on both Mac and Linux; On the [parmes.org/vbox](http://parmes.org/vbox) system the python/scipy/numpy versions are as follows:

```
parmes@parmes-linux:~/Temp/i64_projectile_fem$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy
>>> print scipy.__version__
0.17.0
>>> import numpy
>>> print numpy.__version__
1.11.0
```
Since this is a Python issue and not Solfec per se, as it seems, maybe you could just use the VirtualBox image? You could also try and install [Linux Lite](https://www.linuxliteos.com) yourself, instead of Ubuntu (I could give you a list of installed packages); Then you could use the [parmes.tar.gz archive](http://parmes.org/tgz) to quickly set up Solfec;

I will also have a look into the Python issue itself, as it pops up for you, and if I find out how to go around it, I will let you know;

**Comment by tkoziara** [comment]
Nicolas,
I wasn't able to find out the reason for this issue to come up for you - it seems to have something to do with the way the "M * u" multiplication is resolved; I produced a standalone version of the issue (attached), which you could use when posting to one of [numpy/scipy forums](https://www.scipy.org/scipylib/mailing-lists.html); you can run it as a pure python script;
Best regards,
Tomek
[i64_python_standalone.zip](https://github.com/tkoziara/solfec/files/986018/i64_python_standalone.zip)

**Comment by nicolasmecamas** [comment]
It works now,
Thank Tomek

**Comment by tkoziara** [comment]
OK, I am closing this issue;
