### ISSUE TITLE
Extend RIGID_TO_FEM and INITALIZE_STATE to accept a "subset" parameter

### ISSUE THREAD

**Issue by tkoziara** [tkoziara/solfec#69]
This is motivated by @bencannell comments in [issue 68](https://github.com/tkoziara/solfec/issues/68); The idea is to extend RIGD_TO_FEM and INITIALIZE_STATE commands by a *subset* parameter akin to that in the [XDMF_EXPORT](http://parmes.org/solfec/xdmf/export.html) command in order to facilitate narrower application of these functionalities; also mentioning @stevebrasier so that he can received notifications:)

**Comment by tkoziara** [comment]
Let's start with ``INITIALIZE_STATE (solfec, path, time)``; Currently this command initialises ``solfec`` globally with results from ``path`` assuming a 1-2-1 mapping and using body IDs;
Now, body IDs are input file specific, depend on problem size, etc. They are not very reliable when we work with different models; How about having ``subset`` defined only by label strings like that:
```
INITIALIZE_STATE (solfec, path, time | subset)
where
* subset - defines a subset of initialized bodies; a string can be used to define a POSIX regular
expression that will be matched against body labels; a list of such strings can also be passed;
e.g. [‘^BOD.*A$’, '^BODY1$', '^BODY2$', '^BOD.*B$'] defines two direct labels 'BODY1' and
'BODY2' and two possible subsets made of labels such as 'BODY123A', 'BODY_anything_B', etc.
```
?

**Comment by bencannell** [comment]
Yes, this would work well for us :)

**Comment by tkoziara** [comment]
Hi:) This is now implemented and available; See [docs](http://parmes.org/solfec/user/simulation.html#initialization) and [examples](https://github.com/tkoziara/solfec/tree/master/inp/devel) (named ``initialise-state-{1,2}.py`` and ``rigid-to-fem-{1,2}.py`` and to be run in the ``1,2`` sequence); have a look into uncommenting suitable lines to test the ``subset`` argument; Tomek
