### ISSUE TITLE
HISTORY refinements to support fragmentation

### ISSUE THREAD

**Issue by tkoziara** [tkoziara/solfec#70]
This is is a fork from #67 where it became evident that handling of fragmentation in the HISTORY command will require refinements. Currently we have two ideas for evaluation:

1. Allow for the same syntax as now and track points with fragments. In this case would the users want to know whether the retrieved results actually include fragmentation or not? Would there be another entity that could be outputted to provide this information?

2. Let the HISTORY command tuple (body, point, entity) also handle a string label in place of the 'body'. This way the history of labeled fragments could be retrieved only when they existed. Labelling conventions could help associate fragments with parent bodies.

Both of these could possible be implemented. Option 1 may require changes to the output format in order to track fragments ancestry by body IDs. It is not clear, at the time of writing this, whether this can be implemented without substantial refinements. Option 2 seems easier to add at first glance.

**Comment by bencannell** [comment]
Steve and I have discussed and we agree that Option 2 looks like the preferred solution.

To clarify, please can "point" be defined as the point on the body at t=0s?

So, for example, if body1 was fragmented producing body2 and body3, results could be accessed on body2 by the following command:

HISTORY(body2.label, point, entity)

Where "point" is the equivalent point at t=0 on body1.

In addition, if body1.label == body2.label, then the above command would return HISTORY() results across the whole history, noting that the body the results are being extracted from would change following the fragmentation.

Similarly, if body1.label != body2.label, then the above command would return HISTORY() results across the whole history although the history values would be "nan" whilst body2 did not exist.

**Comment by tkoziara** [comment]
Yes, these are reasonable assumptions; the last one helps to preserve the current format of the HISTORY command, where only one history of time instances is returned;

Perhaps also, for fragments, it would be possible to return tuples (tt, vv) storing their own time interval and value vectors; that could be an option instead of NANs;

**Comment by tkoziara** [comment]
@bencannell @stevebrasier FYI, I have now implemented the idea with passing body labels and receiving NANs when the body is not present; See [docs](http://parmes.org/solfec/user/results.html#history) and [example](https://github.com/tkoziara/solfec/blob/master/inp/devel/rt_split.py#L61);

**Comment by bencannell** [comment]
@tkoziara Thanks for making this update! I have a few questions based on some initial tests.

I've been testing the updated HISTORY function using this modified version of your example [rt_split.txt](https://github.com/tkoziara/solfec/files/1401853/rt_split.txt). I've added some print statements and changed the split such that the 'pipe' body is split into two bodies.

Firstly, HISTORY doesn't behave exactly as discussed in https://github.com/tkoziara/solfec/issues/70#issuecomment-322742436. In the test case, one of the two fragments produced using RT_SPLIT returns the body.label = 'pipe'. As such, I would expect a the command `HISTORY (sol, ('pipe',pnt, 'DZ'), dur[0], dur[1])` to return a complete history of DZ values for the bodies with label 'pipe' (despite the label moving to a different body during the simulation). Instead, results are returned for the body which was first labelled 'pipe'. Would it be possible to update solfec to handle this case? It's useful for us to be able to maintain component labels throughout a whole simulation, and just apply new labels to the fragments which we detach from the bulk of a component.

Secondly, while investigating the behaviour of the above, I've noticed what appear to be inconsistencies in the identification of solfec objects. I'd be interested to here your thoughts regarding the following queries:

1. Why does `solfec.bodies` return different object references to accessing body objects using the command `BYLABEL(solfec, 'BODY', ...)`? 

1. Why does accessing body object references by looping through solfec.bodies and calling `BYLABEL(solfec, 'BODY', ...)` appear to return the same `solfec.BODY` object even though the python `id(BODY)` is unique?

2. Following a split, the BODY.id values appear to be updated as expected for the split bodies and retained for the unsplit bodies. However, why are the `solfec.BODY` and python `id(BODY)` different before and after the split? I would expect the objects to be exactly the same if not modified during the split.

1. For consistency, would it make sense to update the python `id(BODY)` to return the same value as `BODY.id`?

The above queries are based on the printed output in [rt_split.txt](https://github.com/tkoziara/solfec/files/1401853/rt_split.txt).

**Comment by tkoziara** [comment]
Hi Ben,

To address the issue with HISTORY I will take a little time. I can reply to your points first:

1. Python BODY objects are created on the fly whenever a user asks for a BODY object that represents a Solfec body. For every new call that returns a BODY object with the same Solfec identifier the corresponding Python BODY will be **different**. They are just wrappers. So for example:

``bod1 = BYLABEL (solfec, 'BODY', 'bod1label')``
``bod2 = BYLABEL (solfec, 'BODY', 'bod1label')``
``print bod1 == bod2``

will print out ``False``

2. The python id() function bears no relevance in the context of Solfec identifiers. This is a Python feature that I just learnt about from you. Solfec does not provide any means of interfacing with the Python id() function.

3. See 2.

4. See 2.

Thank you for providing the modified example. I will be looking into it next.
Tomek

**Comment by bencannell** [comment]
Hi Tomek, thanks for the clarification

FYI @stevebrasier

**Comment by tkoziara** [comment]
Ben, @stevebrasier 
You can try now; Thank you for spotting; This was about how re-labeled bodies were internally mapped when the same label was being reused;

**Comment by bencannell** [comment]
@tkoziara 
Thanks Tomek. I've just tested this using the [rt_split](https://github.com/tkoziara/solfec/files/1401853/rt_split.txt) file. The update means that the simulation no longer outputs nans following the split, however it appears that the results at the time of splitting are copied across the remaining time history. Any ideas?

**Comment by tkoziara** [comment]
Just had a quick look and couldn't quite see why this would be the case - which it indeed is. I will have a proper look on Monday. Thanks.

**Comment by tkoziara** [comment]
A wee bug. Have a try now:)

**Comment by tkoziara** [comment]
Hey @bencannell ; ok to close this one now?

**Comment by bencannell** [comment]
Hi @tkoziara, yes ok to close :)
