### ISSUE TITLE
FORWARD command

### ISSUE THREAD

**Issue by bencannell** [tkoziara/solfec#75]
Hi @tkoziara,

I think the FORWARD command is broken. As an example, running your test [amt.py](https://github.com/tkoziara/solfec/blob/master/inp/amt.py) doesn't output results in read mode (i.e. the post-processing of results doesn't get past the first time increment.

Or perhaps this observation is pointing at a general issue with using the FORWARD/SEEK commands to loop through object properties while solfec is in READ mode?

I am using solfec changeset fd106b2.

Many thanks :)

Ben

(mention @stevebrasier)

**Comment by bencannell** [comment]
mention @stevebrasier

**Comment by tkoziara** [comment]
thanks for spotting; simple bug; fixed at d7146a6; closing:)

**Comment by bencannell** [comment]
Thanks @tkoziara. This works now :)

Ben
